CREATE TABLE Categorie (
    Nom_categorie VARCHAR(50) PRIMARY KEY,
    description CLOB
);

CREATE TABLE Salle_de_vente (
    ID_salle_vente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nom_categorie VARCHAR(50) NOT NULL,
    CONSTRAINT fk_salle_categorie FOREIGN KEY (Nom_categorie)
    REFERENCES Categorie(Nom_categorie)
);


CREATE TABLE Produit (
    ID_produit INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL UNIQUE,
    prix_revient FLOAT NOT NULL,
    Nom_categorie VARCHAR(50) NOT NULL,
    CONSTRAINT fk_produit_categorie FOREIGN KEY (Nom_categorie)
    REFERENCES Categorie(Nom_categorie),
    CONSTRAINT chk_prix_revient CHECK (prix_revient > 0)
);


CREATE TABLE Caracteristique (
    ID_produit INT NOT NULL,
    Nom_Caracteristique VARCHAR(50) NOT NULL,
    valeur CLOB,
    PRIMARY KEY (ID_produit, Nom_Caracteristique),
    CONSTRAINT fk_caracteristique_produit FOREIGN KEY (ID_produit)
    REFERENCES Produit(ID_produit) ON DELETE CASCADE
);

CREATE TABLE Utilisateur (
    mail VARCHAR(50) PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    adresse CLOB NOT NULL,
    CONSTRAINT chk_mail_format CHECK (mail LIKE '%@%.%')
);


CREATE TABLE Vente (
    ID_Vente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    montante NUMBER(1) DEFAULT 1, -- 1 = TRUE, 0 = FALSE
    limite_offre NUMBER(1) DEFAULT 0, -- pareil
    revocable NUMBER(1) DEFAULT 0, -- pareil
    prix_depart FLOAT NOT NULL,
    date_fin TIMESTAMP DEFAULT NULL, -- J'ai changé vers un TIMESTAMP pour avoir les heures minutes et secondes avant c'était à DATE
    prix_descente FLOAT DEFAULT 0,
    Stock_lot INT NOT NULL,
    ID_salle_vente INT NOT NULL,
    ID_produit INT NOT NULL,
    mail VARCHAR(50) NOT NULL,
    CONSTRAINT fk_vente_salle FOREIGN KEY (ID_salle_vente)
    REFERENCES Salle_de_vente(ID_salle_vente) ON DELETE CASCADE,
    CONSTRAINT fk_vente_produit FOREIGN KEY (ID_produit)
    REFERENCES Produit(ID_produit),
    CONSTRAINT fk_vente_utilisateur FOREIGN KEY (mail)
    REFERENCES Utilisateur(mail) ON DELETE CASCADE,
    CONSTRAINT chk_prix_depart CHECK (prix_depart >= 0),
    CONSTRAINT chk_Stock_lot CHECK (Stock_lot >= 0)
);

CREATE TABLE Offre (
    ID_offre INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    mail VARCHAR(50) NOT NULL,
    ID_Vente INT NOT NULL,
    date_offre TIMESTAMP NOT NULL, -- J'ai changé vers un TIMESTAMP pour avoir les heures minutes et secondes avant c'était à DATE
    prix_achat FLOAT NOT NULL,
    quantite INT NOT NULL,
    CONSTRAINT fk_offre_utilisateur FOREIGN KEY (mail)
    REFERENCES Utilisateur(mail) ON DELETE CASCADE,
    CONSTRAINT fk_offre_vente FOREIGN KEY (ID_Vente)
    REFERENCES Vente(ID_Vente) ON DELETE CASCADE,
    CONSTRAINT chk_prix_achat CHECK (prix_achat >= 0),
    CONSTRAINT chk_quantite CHECK (quantite > 0)
);

CREATE VIEW Prix_achat AS
    SELECT MAX(prix_achat/quantite) AS ratio, ID_Vente FROM Offre GROUP BY ID_Vente;